export class SelectionItems {
    public static names = [
        'date_added',
        // 'objectId',
        'filial',
    ];

    public static names2 = [
        // 'residentialComplex',
        // 'year'
    ];

    public static items = {
        date_added: {
            name: 'date_added',
            title: 'Объекты за период от до',
            value: '0',
            type: 'date_added',
            primary_key_name: '',
            primary_key_table: '',
            value_string: '',
            query: '',
            value_name: '',
            title_default: '',
            value_default: '',
            value_table: '',
            value_primary_key: '',
            value_field: '',
            assign_to: '',
            dbtype: '1',
            table_name: 'data',
            primary_key: '',
            primary_key_value: '',
            action: '',
            tab: '',
            hint: '',
            active_in_topic: '0',
            entity: '',
            parameters: [],
            required: 'off',
            required_boolean: '0',
            unique: 'off',
            columns_id: '57',
            table_id: '7',
            active: '1'
        },

        // objectId: {
        //     name: 'objectId',
        //     title: 'Поиск по ID',
        //     value: '0',
        //     type: 'select_by_query_multi',
        //     primary_key_name: '',
        //     primary_key_table: '',
        //     value_string: '',
        //     query: '',
        //     value_name: '',
        //     title_default: '',
        //     value_default: '',
        //     value_table: '',
        //     value_primary_key: '',
        //     value_field: '',
        //     assign_to: '',
        //     dbtype: '1',
        //     table_name: 'data',
        //     primary_key: '',
        //     primary_key_value: '',
        //     action: '',
        //     tab: '',
        //     hint: '',
        //     active_in_topic: '0',
        //     entity: '',
        //     parameters: [],
        //     required: 'off',
        //     required_boolean: '0',
        //     unique: 'off',
        //     columns_id: '57',
        //     table_id: '7',
        //     active: '1'
        // },

        filial: {
            name: 'filial',
            title: 'Филиал',
            value: '0',
            type: 'select_by_query_multi',
            primary_key_name: '',
            primary_key_table: '',
            value_string: '',
            query: '',
            value_name: '',
            title_default: '',
            value_default: '',
            value_table: '',
            value_primary_key: '',
            value_field: '',
            assign_to: '',
            dbtype: '1',
            table_name: 'data',
            primary_key: '',
            primary_key_value: '',
            action: '',
            tab: '',
            hint: '',
            active_in_topic: '0',
            entity: '',
            parameters: [],
            required: 'off',
            required_boolean: '0',
            unique: 'off',
            columns_id: '57',
            table_id: '7',
            active: '1'
        }
    };

    public static items2 = {
        // residentialComplex: {
        //     name: 'residentialComplex',
        //     title: 'Жилой комплекс',
        //     value: '0',
        //     type: 'residentialComplex',
        //     primary_key_name: '',
        //     primary_key_table: '',
        //     value_string: '',
        //     query: '',
        //     value_name: '',
        //     title_default: '',
        //     value_default: '',
        //     value_table: '',
        //     value_primary_key: '',
        //     value_field: '',
        //     assign_to: '',
        //     dbtype: '1',
        //     table_name: 'data',
        //     primary_key: '',
        //     primary_key_value: '',
        //     action: '',
        //     tab: '',
        //     hint: '',
        //     active_in_topic: '0',
        //     entity: '',
        //     parameters: [],
        //     required: 'off',
        //     required_boolean: '0',
        //     unique: 'off',
        //     columns_id: '57',
        //     table_id: '7',
        //     active: '1'
        // },
        // year: {
        //     name: 'year',
        //     title: 'Год постройки',
        //     value: '0',
        //     type: 'year',
        //     primary_key_name: '',
        //     primary_key_table: '',
        //     value_string: '',
        //     query: '',
        //     value_name: '',
        //     title_default: '',
        //     value_default: '',
        //     value_table: '',
        //     value_primary_key: '',
        //     value_field: '',
        //     assign_to: '',
        //     dbtype: '1',
        //     table_name: 'data',
        //     primary_key: '',
        //     primary_key_value: '',
        //     action: '',
        //     tab: '',
        //     hint: '',
        //     active_in_topic: '0',
        //     entity: '',
        //     parameters: [],
        //     required: 'off',
        //     required_boolean: '0',
        //     unique: 'off',
        //     columns_id: '57',
        //     table_id: '7',
        //     active: '1'
        // }
    };
}
